BASE_URL = 'https://api.practitest.com'
INSTANCES_PATH = '/api/v2/projects/{projectId}/instances.json?set-ids={testSetId}'
TESTS_PATH = '/api/v2/projects/{projectId}/tests.json?display-ids={testDisplayIds}'
STEPS_PATH = '/api/v2/projects/{projectId}/steps.json?test-ids={testIds}'
TEST_PATH = '/api/v2/projects/{projectId}/tests/{testId}.json'
CUSTOM_FIELDS_PATH = '/api/v2/projects/{projectId}/custom_fields.json'
RUNS_PATH = '/api/v2/projects/{projectId}/runs.json'
